### ISSUE TITLE
How should I use multistep prop mode?

### ISSUE THREAD

**Issue by Da1sypetals** [fangwei123456/spikingjelly#591]
**Issue type**
- [ ] Help wanted

**SpikingJelly version**

latest stable

**Description**

How should I use multistep prop mode? I would like shape `[T,N,*]` as input. 
My code is like this:
```py
from spikingjelly.activation_based.neuron import LIFNode
from spikingjelly.activation_based import functional
import torch

layer = LIFNode(step_mode="m").to("cuda")
functional.set_step_mode(layer, "m")

img_shape = (4, 4, 3)

x = torch.randn(12, 13, *img_shape).to("cuda")
layer(x)
x = torch.randn(9, 3, *img_shape).to("cuda")
layer(x)
```
But I get error: 
```
File "<...>/miniconda3/envs/sup/lib/python3.10/site-packages/spikingjelly/activation_based/neuron.py", line 742, in fallback_function
    @torch.jit.script
    def neuronal_charge_decay_input_reset0(x: torch.Tensor, v: torch.Tensor, tau: float):
        v = v + (x - v) / tau
                 ~~~~~ <--- HERE
        return v
RuntimeError: The size of tensor a (3) must match the size of tensor b (13) at non-singleton dimension 0
```
which originates from the last line of code.

I read the docs and did what the docs did but still got this error. 

![image](https://github.com/user-attachments/assets/1eb848fb-79a5-4325-8c44-af3d0ea16b47)

Did I missed something? If possible, a minimal runnable example would be helpful. Thanks a lot! ❤️ ❤️ ❤️

**Comment by Slypi** [comment]
Hi, your error is not really linked to the step_mode. Since neuron layers are stateful, they retain the shape of your input. Hence, you cannot change N (or the img_shape) without first resetting the network with `layer.reset()` or `functional.reset_net(yourNet)` in-between the inputs of different shape.

The errors shows that it was expecting a N=13 but received N=3 when you tried to feed your second input because it retained the shape of the 1st input. So simply resetting correctly your network between the two should work.

Hope this helps !
